#!/usr/bin/env bash

DATA_DIR="$(pwd)/log"
echo "🟢 DATA_DIR: ${DATA_DIR}"

SERVICE_COUNT=3

# Aeron version we are using
VERSION=1.46.2
ARCHIVE_DIR=${DATA_DIR}/archive

# SHARED MEMORY FOLDER
MEM_DIR=${DATA_DIR}/memdir

# DISK FOLDER
DISK_DIR=${DATA_DIR}/diskdir
echo "🟢 DISK_DIR: ${DISK_DIR}"
# PORT CONFIGS
PORT_BASE=9000
PORTS_PER_NODE=100
ARCHIVE_CONTROL_PORT_OFFSET=1
CLIENT_FACING_PORT_OFFSET=2
MEMBER_FACING_PORT_OFFSET=3
LOG_PORT_OFFSET=4
TRANSFER_PORT_OFFSET=5
LOG_CONTROL_PORT_OFFSET=6
REPLICATION_PORT_OFFSET=7

# THREADING MODE
THREADING="SHARED"

# DEBUG
DEBUG=false

HOSTS=("localhost" "localhost" "localhost")
